-- Add sortOrder/isActive fields for service admin modules
ALTER TABLE `ServiceMenu` ADD COLUMN `sortOrder` INTEGER NOT NULL DEFAULT 0, ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `Technology` ADD COLUMN `sortOrder` INTEGER NOT NULL DEFAULT 0, ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `Benefit` ADD COLUMN `sortOrder` INTEGER NOT NULL DEFAULT 0, ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `ContactButton` ADD COLUMN `sortOrder` INTEGER NOT NULL DEFAULT 0, ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `ServiceProcess` ADD COLUMN `sortOrder` INTEGER NOT NULL DEFAULT 0, ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `HireService` ADD COLUMN `sortOrder` INTEGER NOT NULL DEFAULT 0, ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `WhyService` ADD COLUMN `sortOrder` INTEGER NOT NULL DEFAULT 0, ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `WhyVedxReason` ADD COLUMN `sortOrder` INTEGER NOT NULL DEFAULT 0, ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;
